name: evaseafinal
description: EvalSea Authentication App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  url_launcher: ^6.2.6
  shimmer: ^3.0.0

  # ðŸ”¥ FIXED VERSION
  file_picker: ^8.0.0
  permission_handler: ^11.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
